project_name         = "swiggy"
environment          = "dev"
vpc_cidr             = "10.0.0.0/16"
public_subnet_cidrs  = ["10.0.10.0/24", "10.0.11.0/24"]
private_subnet_cidrs = ["10.0.1.0/24", "10.0.2.0/24"]
availability_zones   = ["ap-south-1a", "ap-south-1b"]
container_image_uri  = "ACCOUNT_ID.dkr.ecr.ap-south-1.amazonaws.com/swiggy-app-dev:latest"
ami_id               = "ami-0388e3ada3d9812da"
instance_type        = "t3.medium"
key_name             = "swiggy-key"                        
s3_bucket_name       = "swiggy-alb-logs-dev-pravin"